name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/Bunkograph.Web/Dockerfile --tag hamsterexastris/bunkographweb:$IMAGE_TAG
    
    - name: Upload the Docker image
      run: docker push hamsterexastris/bunkographweb:$IMAGE_TAG
    
    - run: echo $(date +%s)
